### ISSUE TITLE
不知如何使用这脚本

### ISSUE THREAD

**Issue by GitHub-Titanium** [will7101/fgo-bot#2]
按照步骤操作无法实现预期效果（确切的说是毫无动静），运行过程如附图示，望解答如何操作这脚本，最好能录段视频共享至B站或此类网站，感谢！

**Comment by GitHub-Titanium** [comment]
按照步骤操作无法实现预期效果（确切的说是毫无动静），运行过程如下代码段示，望解答如何操作这脚本，最好能录段视频共享至B站或此类网站，感谢！

INFO:device:OK device connected.
INFO:bot:Entering battle...
DEBUG:bot:Wait until image 'menu' appears.
DEBUG:device:Capturing screen from shell...
DEBUG:device:Executing command: adb shell screencap -p
DEBUG:device:Sanitizing png bytes...
DEBUG:device:Pattern detected: 'b'\r\r\n''
DEBUG:tm:Screen updated.
DEBUG:tm:max_val = 0.7358049750328064, max_loc = (1154, 665)
DEBUG:bot:Sleep 2 seconds.
DEBUG:device:Capturing screen from shell...
DEBUG:device:Executing command: adb shell screencap -p
DEBUG:device:Sanitizing png bytes...
DEBUG:device:Pattern detected: 'b'\r\r\n''
DEBUG:tm:Screen updated.

**Comment by will7101** [comment]
不好意思哈，这个脚本是两年前我自己写着玩的，现在版本可能已经不适配了，本身写的也不是很好，如果想要自动刷图的话建议还是找别的工具吧XD
