### ISSUE TITLE
作者不维护了吗？

### ISSUE THREAD

**Issue by Younsion** [will7101/fgo-bot#5]
现在文本啥的都改了，不维护了吗？

**Comment by williamgateszhao** [comment]
请看pull requests，我修改的版本可以用，而且还有很大提升

**Comment by Younsion** [comment]
👍666，下次试试你的~
我当时新圣诞也在本地改了一版刷无限池，这个脚本瓶颈好像主要在截图，我这边统计截图耗时平均要2-5s，太长了，不知道有没有啥优化方法（当时才刷了130池😭）

**Comment by williamgateszhao** [comment]
把分辨率改小……在cpu性能不足的情况下效果很明显

**Comment by Younsion** [comment]
嗖嘎...
